# Vit Transformer

## Модель

In [1]:
import torch
from torch import nn

In [2]:
# Смоделируем данные

n_features = 10  # Количество признаков
n_classes = 3  # Количество классов
batch_size = 5

data = torch.randn((batch_size, n_features))
print(data.shape)
print(data)

torch.Size([5, 10])
tensor([[-1.2294,  0.9040, -0.1200,  1.0714,  0.5192, -1.2210, -0.0639, -0.2710,
          2.3938,  0.7388],
        [ 1.4390,  1.0446,  0.9967,  2.4745, -1.3781,  0.4461,  1.5490,  0.3204,
          0.8215, -1.1460],
        [ 2.1096,  0.3937,  1.6926, -1.3716, -0.5218, -0.9493,  1.7596, -0.7344,
          0.0625, -0.2907],
        [-0.9791, -0.3166,  0.5805, -2.3791,  0.3706, -0.5217,  1.9911, -1.1256,
          1.0570,  0.5330],
        [-1.2397,  1.5370, -0.1331, -0.5572, -0.0576, -0.9227,  0.5054,  0.9964,
         -0.7011,  0.3662]])


In [ ]:
# Зададим простую модель
model = nn.Linear(n_features, n_classes)

In [ ]:
# Применим модель к вектору
answer = model(data)
print(answer.shape)
print(answer)

torch.Size([5, 3])
tensor([[-0.1430, -0.1978, -0.2459],
        [ 0.0568,  0.2415,  1.2328],
        [ 0.3432,  0.4882, -0.8710],
        [-0.0182,  0.0482,  0.2527],
        [ 0.3254, -0.0420,  0.0331]], grad_fn=<AddmmBackward>)


In [ ]:
# Модель как наследник nn.Module
class SimpleNN(nn.Module):
    def __init__(self, n_features, n_classes):
        super().__init__()

        self.lin = nn.Linear(n_features, n_classes)

    def forward(self, x):
        return self.lin(x)

In [ ]:
# Попробуем применить модель в виде класса к данным
model = SimpleNN(n_features, n_classes)

answer = model(data)
print(answer.shape)
print(answer)

torch.Size([5, 3])
tensor([[ 0.5724,  0.0264, -0.9001],
        [ 0.3813,  0.7960, -0.4653],
        [ 0.2878, -0.9297, -0.8761],
        [-0.4443, -0.0975, -0.2454],
        [-0.1670, -0.1594,  0.1794]], grad_fn=<AddmmBackward>)


In [ ]:
!pip install torchsummary
from torchsummary import summary

model = SimpleNN(n_features, n_classes).cuda()

# 5, 10
input_size = (batch_size, n_features)
print(summary(model, input_size))

You should consider upgrading via the '/home/yessense/PycharmProjects/scene_vae/venv/bin/python -m pip install --upgrade pip' command.
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 5, 3]              33
Total params: 33
Trainable params: 33
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
None


In [ ]:
# Модель как sequential
model = nn.Sequential(nn.Linear(n_features, n_classes))

answer = model(data)
print(answer.shape)
print(answer)

In [ ]:
# Модель как nn.ModuleList

model = nn.ModuleList([nn.Linear(n_features, n_classes)])

# answer = model(data)
# print(answer.shape)
# print(answer)

answer = model[0](data)
print(answer.shape)
print(answer)


torch.Size([5, 3])
tensor([[-0.3989, -1.1825,  0.7602],
        [-0.0798,  0.7053, -0.0033],
        [-0.2838, -0.0166, -0.5549],
        [-0.1167,  0.6097, -0.4273],
        [-0.2631,  0.2675, -0.2055]], grad_fn=<AddmmBackward>)


In [ ]:
# Проверим параметры модели
class ParametersCheck(nn.Module):
    def __init__(self, n_features, n_classes):
        super().__init__()

        self.lin = nn.Linear(n_features, n_classes)
        self.seq = nn.Sequential(nn.Linear(n_features, n_classes))
        self.module_list = nn.ModuleList([nn.Linear(n_features, n_classes)])
        self.list_of_layers = [nn.Linear(n_features, n_classes)]


In [ ]:
model = ParametersCheck(n_features, n_classes)

for i, param in enumerate(model.parameters()):
    print(f'Параметр #{i + 1}.')
    print(f'\t{param.shape}')

Параметр #1.
	torch.Size([3, 10])
Параметр #2.
	torch.Size([3])
Параметр #3.
	torch.Size([3, 10])
Параметр #4.
	torch.Size([3])
Параметр #5.
	torch.Size([3, 10])
Параметр #6.
	torch.Size([3])


## ViT

![alt text](https://drive.google.com/uc?export=view&id=1J5TvycDPs8pzfvlXvtO5MCFBy64yp9Fa)

In [2]:
!pip install einops

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 1.1 MB/s eta 0:00:00


In [5]:
import torch
import torch.nn.functional as F
# import matplotlib.pyplot as plt

from torch import nn
from torch import Tensor
from PIL import Image
from torchvision.transforms import Compose, Resize, ToTensor
from einops import rearrange, reduce, repeat
from einops.layers.torch import Rearrange, Reduce
# from torchsummary import summary

![](https://amaarora.github.io/images/vit-01.png)

## Часть 1. Patch Embedding, CLS Token, Position Encoding

![](https://amaarora.github.io/images/vit-02.png)

In [ ]:
# input image `B, C, H, W`
x = torch.randn(1, 3, 224, 224)
# 2D conv
conv = nn.Conv2d(3, 768, 16, 16)
conv(x).reshape(-1, 196).transpose(0,1).shape

torch.Size([196, 768])

In [6]:
class PatchEmbedding(nn.Module):
    """ Image to Patch Embedding
    """
    def __init__(self, img_size=224, patch_size=16, in_chans=3, embed_dim=768):
        super().__init__()

        self.patch_embeddings = nn.Sequential(
            nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size),
            Rearrange('b c h w -> b (h w) c')
        )

        self.position_embeddings = nn.Parameter(torch.randn(1, (img_size // patch_size) ** 2 + 1, embed_dim))
        self.cls_token = nn.Parameter(torch.randn(1, 1, embed_dim))

    def forward(self, x: Tensor) -> Tensor:

        patches = self.patch_embeddings(x)
        patches = torch.cat((patches, repeat(self.cls_token, '() n e -> b n e', b=x.shape[0])), dim=1)
        patches += repeat(self.position_embeddings, '() n e -> b n e', b=x.shape[0])

        return patches

In [7]:
patch_embed = PatchEmbedding()
x = torch.randn(1, 3, 224, 224)
patch_embed(x).shape

torch.Size([1, 197, 768])

![](https://amaarora.github.io/images/vit-03.png)

## Часть 2. Transformer Encoder

![](https://amaarora.github.io/images/ViT.png)

![](https://amaarora.github.io/images/vit-07.png)

In [8]:
class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, drop=0.):
        super().__init__()

        hidden_features = hidden_features or in_features
        out_features = out_features or in_features

        # Linear Layers
        self.nn = nn.Sequential(
            nn.Linear(in_features=in_features, out_features=hidden_features),
            nn.ReLU(),
            nn.Dropout(p=drop),
            nn.Linear(in_features=hidden_features, out_features=out_features),
            nn.Dropout(p=drop),
            nn.ReLU(),
        )

        # Activation(s)
        self.relu = nn.ReLU()
        

    def forward(self, x):

        x = self.nn(x)
        x = self.relu(x)

        return x

In [9]:
x = torch.randn(1, 197, 768)
mlp = MLP(768, 3072, 768)
out = mlp(x)
out.shape

torch.Size([1, 197, 768])

In [36]:
class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., out_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        self.head_dim = dim // num_heads
        self.scale = self.head_dim ** -0.5

        self.qkv = nn.Sequential(
            nn.Linear(in_features=dim, out_features=3*dim, bias=qkv_bias),
            # torch.view()
            # Rearrange('b n (k h e) -> b n k h e', h=num_heads, e=head_dim, k=3)            
        )
        self.attn_drop = nn.Dropout(attn_drop)
        self.out = ...
        self.out_drop = nn.Dropout(out_drop)

    def forward(self, x):
        
        (b, n, e) = x.shape
        # Attention
        qkv = self.qkv(x)
        qkv = qkv.view(b, n, 3, self.num_heads, self.head_dim)
        print(qkv.shape)
        q, k, v = torch.split(qkv, [1, 1, 1], dim=2)
        print(q.shape, k.shape, v.shape)
        # k = k.transpose(-2, -1)
        # attention = (q @ k) * self.scale

        # Out projection

        ...

        return x


![](https://amaarora.github.io/images/vit-08.png)

In [ ]:
# attn = (q @ k.transpose(-2, -1)) * self.scale
# attn = attn.softmax(dim=-1)

In [37]:
x = torch.randn(1, 197, 768)
attention = Attention(768, 12)
out = attention(x)
out.shape

torch.Size([1, 197, 3, 12, 64])
torch.Size([1, 197, 1, 12, 64]) torch.Size([1, 197, 1, 12, 64]) torch.Size([1, 197, 1, 12, 64])


torch.Size([1, 197, 768])

In [ ]:
class Block(nn.Module):
    def __init__(self, dim, num_heads=8, mlp_ratio=4, drop_rate=0.):
        super().__init__()

        # Normalization
        self.norm1 = nn.LayerNorm()

        # Attention
        ...

        # Dropout
        ...

        # Normalization
        self.norm2 = nn.LayerNorm()

        # MLP
        self.MLP = MLP(768, 3072, 768)


    def forward(self, x):
        # Attetnion
        ...

        # MLP
        ...
        return x

In [ ]:
x = torch.randn(1, 197, 768)
block = Block(768, 8)
out = attention(x)
out.shape

torch.Size([1, 197, 768])

В оригинальной реализации теперь используется [DropPath](https://github.com/rwightman/pytorch-image-models/blob/e98c93264cde1657b188f974dc928b9d73303b18/timm/layers/drop.py)

In [ ]:
class Transformer(nn.Module):
    def __init__(self, depth, dim, num_heads=8, mlp_ratio=4, drop_rate=0.):
        super().__init__()
        self.blocks = nn.ModuleList([
            Block(dim, num_heads, mlp_ratio, drop_rate)
            for i in range(depth)])

    def forward(self, x):
        for block in self.blocks:
            x = block(x)
        return x

In [ ]:
x = torch.randn(1, 197, 768)
block = Transformer(12, 768)
out = attention(x)
out.shape

torch.Size([1, 197, 768])

![](https://amaarora.github.io/images/vit-06.png)

In [ ]:
from torch.nn.modules.normalization import LayerNorm

class ViT(nn.Module):
    """ Vision Transformer with support for patch or hybrid CNN input stage
    """
    def __init__(self, img_size=224, patch_size=16, in_chans=3, num_classes=1000,
                 embed_dim=768, depth=12, num_heads=12, mlp_ratio=4.,
                 qkv_bias=False, drop_rate=0.,):
        super().__init__()

        # Присвоение переменных
        ...

        # Path Embeddings, CLS Token, Position Encoding
        ...

        # Transformer Encoder
        ...

        # Classifier
        ...

    def forward(self, x):

        # Path Embeddings, CLS Token, Position Encoding
        ...

        # Transformer Encoder
        ...

        # Classifier
        ...

        return x

In [ ]:
x = torch.randn(1, 3, 224, 224)
vit = ViT()
out = vit(x)
out.shape

torch.Size([1, 1000])

# Домашнее задание


1. Выбрать датасет для классификации изображений с размерностью 64x64+
2. Обучить ViT на таком датасете.
3. Попробовать поменять размерности и посмотреть, что поменяется при обучении.


Примечание:
- Датасеты можно взять [тут](https://pytorch.org/vision/stable/datasets.html#built-in-datasets) или найти в другом месте.
- Из за того, что ViT учится медленно, количество примеров в датасете можно ограничить до 1к-5к.